cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path("index/", views.index, name='index'),
    path("calendar/", views.CalendarView.as_view(), name="calendar"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    list_projects,
    show_project,
    create_project,
    project_list_update,
    project_list_delete,
    ProjectTimelineView,
)


urlpatterns = [
    path("", list_projects, name="list_projects"),
    path("<int:id>/", show_project, name="show_project"),
    path("create/", create_project, name="create_project"),
    path("<int:id>/edit/", project_list_update, name="project_list_update"),
    path("<int:id>/delete/", project_list_delete, name="project_list_delete"),
    path("<int:project_id>/timeline/", ProjectTimelineView.as_view(), name="project_timeline"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_home(request):
    return redirect("list_projects")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("", redirect_to_home, name="home"),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("cal/", include("cal.urls")),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

projects/forms.py
from django.forms import ModelForm
from projects.models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = (
            "name",
            "description",
            "owner",
        )

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from projects.models import Project
from django.contrib.auth.decorators import login_required
from projects.forms import ProjectForm
from tasks.models import Task
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


@login_required
def list_projects(request):
    project_list = Project.objects.filter(owner=request.user)
    context = {
        "project_list": project_list,
    }
    return render(request, "projects/list.html", context)


@login_required
def show_project(request, id):
    project_detail = get_object_or_404(Project, id=id)
    context = {
        "project_detail": project_detail,
    }
    return render(request, "projects/detail.html", context)


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(False)
            project.owner = request.user
            form.save()
            return redirect("list_projects")
    else:
        form = ProjectForm()
    context = {
        "form": form,
    }
    return render(request, "projects/create.html", context)


@login_required
def project_list_update(request, id):
    project_list_object = get_object_or_404(Project, id=id)
    if request.method == "POST":
        form = ProjectForm(request.POST, instance=project_list_object)
        if form.is_valid():
            list = form.save()
            return redirect("show_project", id=list.id)
    else:
        form = ProjectForm(instance=project_list_object)
    context = {
        "project_list_object": project_list_object,
        "form": form,
    }
    return render(request, "projects/edit.html", context)


@login_required
def project_list_delete(request, id):
    model_instance = Project.objects.get(id=id)
    if request.method == "POST":
        model_instance.delete()
        return redirect("list_projects")
    context = {
        "project_detail": get_object_or_404(Project, id=id)
    }
    return render(request, "projects/delete.html", context)


class ProjectTimelineView(LoginRequiredMixin, ListView):
    login_url = "accounts:login"
    template_name = "projects/project_timeline.html"
    model = Task
    context_object_name = "completed_tasks"

    def get_queryset(self):
        project_id = self.kwargs["project_id"]
        return Task.objects.filter(project_id=project_id).order_by("due_date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs["project_id"]
        project = Project.objects.get(id=project_id)
        context["project"] = project
        context["task_count"] = Task.objects.filter(project_id=project_id).count()
        context["completed_count"] = Task.objects.filter(project_id=project_id, is_completed=True).count()
        return context

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        {% block extra %}
        {% endblock extra %}
    </head>
    <body>
        <header>
            <nav>
                <div class="dropdown">
                    <button class="dropbtn">Menu</button>
                    <div class="dropdown-content">
                        <ul>
                            {% if user.is_authenticated %}
                                <li>
                                    <a href="{% url 'list_projects' %}">My Projects</a>
                                </li>
                                <li>
                                    <a href="{% url 'show_my_tasks' %}">My Tasks</a>
                                </li>
                                <li>
                                    <a href="{% url 'cal:calendar' %}">My Calendar</a>
                                </li>
                                <li>
                                    <a href="{% url 'logout' %}">Logout</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="{% url 'login' %}">Login</a>
                                </li>
                                <li>
                                    <a href="{% url 'signup' %}">Signup</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>